---
on:
  push:
  workflow_dispatch:

jobs:
  quay-build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: akkoma-fe-mastodon
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/evolvingpixie/shrimp-akkoma-fe:latest,ghcr.io/evolvingpixie/shrimp-akkoma-fe:${{ github.ref_name }}
          outputs: type=image,name=target
